/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `A` - 17 or younger
* `B` - 18 to 20
* `C` - 21 to 29
* `D` - 30 to 39
* `E` - 40 to 49
* `F` - 50 to 59
* `G` - 60 or older
* `H` - I prefer not to say
 */
export type AgeGroupEnum = typeof AgeGroupEnum[keyof typeof AgeGroupEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AgeGroupEnum = {
  A: 'A',
  B: 'B',
  C: 'C',
  D: 'D',
  E: 'E',
  F: 'F',
  G: 'G',
  H: 'H',
} as const;
