/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `A` - 2016
* `B` - 2017
* `C` - 2018
* `D` - 2019
* `E` - 2020
* `F` - 2022
* `G` - 2023
* `H` - 2024
 */
export type AgeGroupEnum = typeof AgeGroupEnum[keyof typeof AgeGroupEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AgeGroupEnum = {
  A: 'A',
  B: 'B',
  C: 'C',
  D: 'D',
  E: 'E',
  F: 'F',
  G: 'G',
  H: 'H',
} as const;
