/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `S` - Send
* `A` - Alert
* `F` - Resolve
 */
export type AnnouncementPendingEnum = typeof AnnouncementPendingEnum[keyof typeof AnnouncementPendingEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnnouncementPendingEnum = {
  S: 'S',
  A: 'A',
  F: 'F',
} as const;
