/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type ApplicationsListStatus = typeof ApplicationsListStatus[keyof typeof ApplicationsListStatus] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApplicationsListStatus = {
  A: 'A',
  D: 'D',
  W: 'W',
} as const;
