/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `AI` - Accepted, In-Person
* `AO` - Accepted, Online
* `WI` - Wait-list, In-Person
* `WO` - Wait-list, Online
* `D` - Declined
 */
export type ApplicationStatusEnum = typeof ApplicationStatusEnum[keyof typeof ApplicationStatusEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApplicationStatusEnum = {
  AI: 'AI',
  AO: 'AO',
  WI: 'WI',
  WO: 'WO',
  D: 'D',
} as const;
