/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type ApplicationquestionsListFormType = typeof ApplicationquestionsListFormType[keyof typeof ApplicationquestionsListFormType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApplicationquestionsListFormType = {
  A: 'A',
  R: 'R',
} as const;
