/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * Serializer for question choices
 */
export interface ApplicationQuestionChoice {
  readonly id?: string;
  question: string;
  /**
   * Short code like 'A', 'B', 'Y', 'N', or device keys like 'APPLE_VISION_PRO'
   * @maxLength 24
   */
  choice_key: string;
  /** @maxLength 500 */
  choice_text: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  order?: number;
}
