/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * List of choice_keys from parent that trigger this question. Empty = always show
 */
export type ApplicationQuestionTriggerChoices = {[key: string]: unknown};
