/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `P` - Participant
* `M` - Mentor
* `J` - Judge
 */
export type ApplicationParticipationClassEnum = typeof ApplicationParticipationClassEnum[keyof typeof ApplicationParticipationClassEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApplicationParticipationClassEnum = {
  P: 'P',
  M: 'M',
  J: 'J',
} as const;
