/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { ParticipationCapacityEnum } from './participationCapacityEnum';

/**
 * @nullable
 */
export type ApplicationRequestParticipationCapacity = ParticipationCapacityEnum | null;
