/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { QuestionTypeEnum } from './questionTypeEnum';
import type { ApplicationQuestionTriggerChoices } from './applicationQuestionTriggerChoices';
import type { ApplicationQuestionChoice } from './applicationQuestionChoice';

/**
 * Serializer for application questions with nested choices
 */
export interface ApplicationQuestion {
  readonly id?: string;
  /**
   * Internal identifier like 'hardware_hack_interest'
   * @maxLength 100
   */
  question_key: string;
  question_text: string;
  question_type: QuestionTypeEnum;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  order?: number;
  required?: boolean;
  /**
   * If set, this question only appears based on parent response
   * @nullable
   */
  parent_question?: string | null;
  /** List of choice_keys from parent that trigger this question. Empty = always show */
  trigger_choices?: ApplicationQuestionTriggerChoices;
  readonly choices?: readonly ApplicationQuestionChoice[];
  /**
   * Maximum character length for text responses
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  max_length?: number | null;
  /**
   * Minimum character length for text responses
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  min_length?: number | null;
  /**
   * Placeholder text for text inputs
   * @maxLength 500
   */
  placeholder_text?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
}
