/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { AgeGroupEnum } from './ageGroupEnum';

/**
 * @nullable
 */
export type ApplicationAgeGroup = AgeGroupEnum | null;
