/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * List of choice_keys selected, preserved snapshot
 */
export type ApplicationResponseSelectedKeysSnapshot = {[key: string]: unknown};
