/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `A` - Accepted
* `W` - Waitlist
* `D` - Declined
 */
export type ApplicationStatusEnum = typeof ApplicationStatusEnum[keyof typeof ApplicationStatusEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApplicationStatusEnum = {
  A: 'A',
  W: 'W',
  D: 'D',
} as const;
