/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { ApplicationsListParticipationCapacity } from './applicationsListParticipationCapacity';
import type { ApplicationsListParticipationRole } from './applicationsListParticipationRole';

export type ApplicationsListParams = {
email?: string;
/**
 * * `S` - Student
* `P` - Professional
* `H` - Hobbyist
 */
participation_capacity?: ApplicationsListParticipationCapacity;
/**
 * * `A` - Digital/Creative Designer
* `D` - Developer
* `S` - Domain or other Specialized Skill Expert
* `P` - Project Manager
 */
participation_role?: ApplicationsListParticipationRole;
/**
 * A search term.
 */
search?: string;
};
