/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * {'choice_key': 'choice_text'} at time of response
 */
export type ApplicationResponseChoicesSnapshot = {[key: string]: unknown};
