/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { GenderIdentityEnum } from './genderIdentityEnum';
import type { CountryEnum } from './countryEnum';
import type { RaceEthnicGroupEnum } from './raceEthnicGroupEnum';
import type { AgeGroupEnum } from './ageGroupEnum';
import type { HeardAboutUsEnum } from './heardAboutUsEnum';
import type { DigitalDesignerSkillsEnum } from './digitalDesignerSkillsEnum';
import type { IndustryEnum } from './industryEnum';
import type { HardwareHackDetailEnum } from './hardwareHackDetailEnum';
import type { ApplicationParticipationClassEnum } from './applicationParticipationClassEnum';
import type { ApplicationAgeGroup } from './applicationAgeGroup';
import type { ApplicationDisabilityIdentity } from './applicationDisabilityIdentity';
import type { ApplicationParticipationCapacity } from './applicationParticipationCapacity';
import type { ApplicationStatus } from './applicationStatus';
import type { ApplicationParticipationRole } from './applicationParticipationRole';
import type { ApplicationThemeInterestTrackOne } from './applicationThemeInterestTrackOne';
import type { ApplicationThemeInterestTrackTwo } from './applicationThemeInterestTrackTwo';
import type { ApplicationThemeDetailOne } from './applicationThemeDetailOne';
import type { ApplicationThemeDetailTwo } from './applicationThemeDetailTwo';
import type { ApplicationThemeDetailThree } from './applicationThemeDetailThree';
import type { HardwareHackInterestEnum } from './hardwareHackInterestEnum';

export interface Application {
  readonly id?: string;
  gender_identity: GenderIdentityEnum[];
  nationality: CountryEnum[];
  current_country: CountryEnum[];
  race_ethnic_group: RaceEthnicGroupEnum[];
  previous_participation: AgeGroupEnum[];
  heard_about_us: HeardAboutUsEnum[];
  digital_designer_skills: DigitalDesignerSkillsEnum[];
  industry: IndustryEnum[];
  hardware_hack_detail: HardwareHackDetailEnum[];
  /** @maxLength 100 */
  first_name: string;
  /**
   * @maxLength 100
   * @nullable
   */
  middle_name?: string | null;
  /** @maxLength 100 */
  last_name: string;
  participation_class?: ApplicationParticipationClassEnum;
  /**
   * @maxLength 100
   * @nullable
   */
  current_city?: string | null;
  /**
   * @maxLength 30
   * @nullable
   */
  pronouns?: string | null;
  /** @nullable */
  age_group?: ApplicationAgeGroup;
  /** @maxLength 254 */
  email: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  event_year?: number;
  /**
   * @maxLength 200
   * @nullable
   */
  portfolio?: string | null;
  /**
   * @maxLength 200
   * @nullable
   */
  secondary_portfolio?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  gender_identity_other?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  race_ethnic_group_other?: string | null;
  /** @nullable */
  disability_identity?: ApplicationDisabilityIdentity;
  /** @nullable */
  participation_capacity?: ApplicationParticipationCapacity;
  /**
   * @maxLength 100
   * @nullable
   */
  student_school?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  student_field_of_study?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  occupation?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  employer?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  industry_other?: string | null;
  /**
   * @maxLength 1000
   * @nullable
   */
  specialized_expertise?: string | null;
  /** @nullable */
  status?: ApplicationStatus;
  /** @nullable */
  previously_participated?: boolean | null;
  /** @nullable */
  participation_role?: ApplicationParticipationRole;
  /**
   * @maxLength 2000
   * @nullable
   */
  experience_with_xr?: string | null;
  /**
   * @maxLength 2000
   * @nullable
   */
  experience_contribution?: string | null;
  /**
   * @maxLength 2000
   * @nullable
   */
  theme_essay?: string | null;
  /**
   * @maxLength 2000
   * @nullable
   */
  theme_essay_follow_up?: string | null;
  /** @nullable */
  theme_interest_track_one?: ApplicationThemeInterestTrackOne;
  /** @nullable */
  theme_interest_track_two?: ApplicationThemeInterestTrackTwo;
  /** @nullable */
  theme_detail_one?: ApplicationThemeDetailOne;
  /** @nullable */
  theme_detail_two?: ApplicationThemeDetailTwo;
  /** @nullable */
  theme_detail_three?: ApplicationThemeDetailThree;
  hardware_hack_interest?: HardwareHackInterestEnum;
  /**
   * @maxLength 20
   * @nullable
   */
  heard_about_us_other?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  digital_designer_skills_other?: string | null;
  /**
   * @maxLength 300
   * @nullable
   */
  communications_platform_username?: string | null;
  /**
   * @maxLength 2000
   * @nullable
   */
  outreach_groups?: string | null;
  readonly submitted_at?: string;
  readonly updated_at?: string;
  /**
   * @maxLength 1000
   * @nullable
   */
  mentor_qualified_fields?: string | null;
  /**
   * @maxLength 1000
   * @nullable
   */
  mentor_mentoring_steps?: string | null;
  /** @nullable */
  mentor_previously_mentored?: boolean | null;
  /**
   * @maxLength 1000
   * @nullable
   */
  judge_judging_steps?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  judge_invited_by?: string | null;
  /** @nullable */
  judge_previously_judged?: boolean | null;
  /** @nullable */
  rsvp_email_sent_at?: string | null;
  /** @nullable */
  resume?: string | null;
}
