/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type ApplicationsListParticipationRole = typeof ApplicationsListParticipationRole[keyof typeof ApplicationsListParticipationRole] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApplicationsListParticipationRole = {
  A: 'A',
  D: 'D',
  P: 'P',
  S: 'S',
} as const;
