/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type ApplicationsListParticipationCapacity = typeof ApplicationsListParticipationCapacity[keyof typeof ApplicationsListParticipationCapacity] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApplicationsListParticipationCapacity = {
  H: 'H',
  P: 'P',
  S: 'S',
} as const;
