/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type ApplicationsListStatusesItem = typeof ApplicationsListStatusesItem[keyof typeof ApplicationsListStatusesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApplicationsListStatusesItem = {
  A: 'A',
  D: 'D',
  W: 'W',
} as const;
