/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { ApplicationResponseChoicesSnapshot } from './applicationResponseChoicesSnapshot';
import type { ApplicationResponseSelectedKeysSnapshot } from './applicationResponseSelectedKeysSnapshot';

/**
 * Serializer for application responses with snapshots
 */
export interface ApplicationResponse {
  readonly id?: string;
  question: string;
  question_text_snapshot: string;
  choices_snapshot?: ApplicationResponseChoicesSnapshot;
  selected_keys_snapshot?: ApplicationResponseSelectedKeysSnapshot;
  readonly selected_choice_keys?: readonly string[];
  text_response?: string;
  text_response_snapshot?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
}
