/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { GenderIdentityEnum } from './genderIdentityEnum';
import type { CountryEnum } from './countryEnum';
import type { RaceEthnicGroupEnum } from './raceEthnicGroupEnum';
import type { PreviousParticipationEnum } from './previousParticipationEnum';
import type { HeardAboutUsEnum } from './heardAboutUsEnum';
import type { DigitalDesignerSkillsEnum } from './digitalDesignerSkillsEnum';
import type { IndustryEnum } from './industryEnum';
import type { HardwareHackDetailEnum } from './hardwareHackDetailEnum';
import type { ApplicationResponse } from './applicationResponse';
import type { ParticipationClassA3fEnum } from './participationClassA3fEnum';
import type { ApplicationDetailAgeGroup } from './applicationDetailAgeGroup';
import type { ApplicationDetailDisabilityIdentity } from './applicationDetailDisabilityIdentity';
import type { ApplicationDetailParticipationCapacity } from './applicationDetailParticipationCapacity';
import type { ApplicationDetailStatus } from './applicationDetailStatus';
import type { ApplicationDetailParticipationRole } from './applicationDetailParticipationRole';
import type { ApplicationDetailThemeInterestTrackOne } from './applicationDetailThemeInterestTrackOne';
import type { ApplicationDetailThemeInterestTrackTwo } from './applicationDetailThemeInterestTrackTwo';
import type { ApplicationDetailThemeDetailOne } from './applicationDetailThemeDetailOne';
import type { ApplicationDetailThemeDetailTwo } from './applicationDetailThemeDetailTwo';
import type { ApplicationDetailThemeDetailThree } from './applicationDetailThemeDetailThree';
import type { ApplicationDetailHardwareHackInterest } from './applicationDetailHardwareHackInterest';

/**
 * Detailed application serializer with question responses
 */
export interface ApplicationDetail {
  readonly id?: string;
  gender_identity: GenderIdentityEnum[];
  nationality: CountryEnum[];
  current_country: CountryEnum[];
  race_ethnic_group: RaceEthnicGroupEnum[];
  previous_participation: PreviousParticipationEnum[];
  heard_about_us: HeardAboutUsEnum[];
  digital_designer_skills: DigitalDesignerSkillsEnum[];
  industry: IndustryEnum[];
  hardware_hack_detail: HardwareHackDetailEnum[];
  readonly question_responses?: readonly ApplicationResponse[];
  /** @maxLength 100 */
  first_name: string;
  /**
   * @maxLength 100
   * @nullable
   */
  middle_name?: string | null;
  /** @maxLength 100 */
  last_name: string;
  participation_class?: ParticipationClassA3fEnum;
  /**
   * @maxLength 100
   * @nullable
   */
  current_city?: string | null;
  /**
   * @maxLength 30
   * @nullable
   */
  pronouns?: string | null;
  /** @nullable */
  age_group?: ApplicationDetailAgeGroup;
  /** @maxLength 254 */
  email: string;
  /**
   * @maxLength 200
   * @nullable
   */
  portfolio?: string | null;
  /**
   * @maxLength 200
   * @nullable
   */
  secondary_portfolio?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  gender_identity_other?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  race_ethnic_group_other?: string | null;
  /** @nullable */
  disability_identity?: ApplicationDetailDisabilityIdentity;
  /** @nullable */
  participation_capacity?: ApplicationDetailParticipationCapacity;
  /**
   * @maxLength 100
   * @nullable
   */
  student_school?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  student_field_of_study?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  occupation?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  employer?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  industry_other?: string | null;
  /**
   * @maxLength 1000
   * @nullable
   */
  specialized_expertise?: string | null;
  /**
   * @maxLength 1000
   * @nullable
   */
  other_skills_experiences?: string | null;
  /** @nullable */
  status?: ApplicationDetailStatus;
  /** @nullable */
  previously_participated?: boolean | null;
  /** @nullable */
  participation_role?: ApplicationDetailParticipationRole;
  /**
   * @maxLength 2000
   * @nullable
   */
  experience_with_xr?: string | null;
  /**
   * @maxLength 2000
   * @nullable
   */
  experience_contribution?: string | null;
  /**
   * @maxLength 2000
   * @nullable
   */
  theme_essay?: string | null;
  /**
   * @maxLength 2000
   * @nullable
   */
  theme_essay_follow_up?: string | null;
  /** @nullable */
  theme_interest_track_one?: ApplicationDetailThemeInterestTrackOne;
  /** @nullable */
  theme_interest_track_two?: ApplicationDetailThemeInterestTrackTwo;
  /** @nullable */
  theme_detail_one?: ApplicationDetailThemeDetailOne;
  /** @nullable */
  theme_detail_two?: ApplicationDetailThemeDetailTwo;
  /** @nullable */
  theme_detail_three?: ApplicationDetailThemeDetailThree;
  /** @nullable */
  hardware_hack_interest?: ApplicationDetailHardwareHackInterest;
  /**
   * @maxLength 20
   * @nullable
   */
  heard_about_us_other?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  digital_designer_skills_other?: string | null;
  /**
   * @maxLength 300
   * @nullable
   */
  communications_platform_username?: string | null;
  /**
   * @maxLength 2000
   * @nullable
   */
  outreach_groups?: string | null;
  readonly submitted_at?: string;
  readonly updated_at?: string;
  /**
   * @maxLength 1000
   * @nullable
   */
  mentor_qualified_fields?: string | null;
  /**
   * @maxLength 1000
   * @nullable
   */
  mentor_mentoring_steps?: string | null;
  /** @nullable */
  mentor_previously_mentored?: boolean | null;
  /**
   * @maxLength 1000
   * @nullable
   */
  judge_judging_steps?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  judge_invited_by?: string | null;
  /** @nullable */
  judge_previously_judged?: boolean | null;
  /** @nullable */
  rsvp_email_sent_at?: string | null;
  event: string;
  /** @nullable */
  resume?: string | null;
}
