/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type ApplicationquestionsListParams = {
parent_question?: string;
question_key?: string;
/**
 * A search term.
 */
search?: string;
};
