/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { HardwareHackDetailEnum } from './hardwareHackDetailEnum';

/**
 * @nullable
 */
export type ApplicationHardwareHackDetail = HardwareHackDetailEnum | null;
