/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { AttendeepreferencesListPreference } from './attendeepreferencesListPreference';

export type AttendeepreferencesListParams = {
preferee?: string;
/**
 * * `Y` - Yay
* `N` - Nay
* `T` - Tbd
 */
preference?: AttendeepreferencesListPreference;
preferer?: string;
/**
 * A search term.
 */
search?: string;
};
