/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { AttendeeRSVPCreateRequestParticipationRole } from './attendeeRSVPCreateRequestParticipationRole';
import type { AttendeeRSVPCreateRequestShirtSize } from './attendeeRSVPCreateRequestShirtSize';
import type { DietaryRestrictionsEnum } from './dietaryRestrictionsEnum';
import type { DietaryAllergiesEnum } from './dietaryAllergiesEnum';
import type { AttendeeRSVPCreateRequestUsVisaSupportNationalIdentificationDocumentType } from './attendeeRSVPCreateRequestUsVisaSupportNationalIdentificationDocumentType';
import type { AttendeeRSVPCreateRequestUsVisaSupportCitizenship } from './attendeeRSVPCreateRequestUsVisaSupportCitizenship';
import type { AttendeeRSVPCreateRequestSpecialInterestTrackOne } from './attendeeRSVPCreateRequestSpecialInterestTrackOne';
import type { AttendeeRSVPCreateRequestSpecialInterestTrackTwo } from './attendeeRSVPCreateRequestSpecialInterestTrackTwo';
import type { ParticipationClassEnum } from './participationClassEnum';
import type { AttendeeRSVPCreateRequestLoanerHeadsetPreference } from './attendeeRSVPCreateRequestLoanerHeadsetPreference';

/**
 * Base serializer that automatically scopes foreign key fields to the current event.

This serializer ensures that when validating foreign key relationships,
only objects from the current event are considered valid. This is crucial
for maintaining proper event isolation in the multi-tenant system.

Usage:
    class MySerializer(EventScopedSerializer):
        class Meta:
            model = MyModel
            fields = ['id', 'name', 'foreign_key_field']
 */
export interface AttendeeRSVPCreateRequest {
  /** @maxLength 150 */
  first_name?: string;
  /** @maxLength 150 */
  last_name?: string;
  /** @nullable */
  participation_role?: AttendeeRSVPCreateRequestParticipationRole;
  /** @nullable */
  profile_image?: string | null;
  /**
   * @minLength 1
   * @maxLength 36
   * @nullable
   */
  authentication_id?: string | null;
  /** @nullable */
  application?: string | null;
  /** @maxLength 1000 */
  bio?: string;
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
  /** @nullable */
  shirt_size?: AttendeeRSVPCreateRequestShirtSize;
  /**
   * I.e., a Discord username
   * @minLength 1
   * @maxLength 40
   * @nullable
   */
  communications_platform_username?: string | null;
  dietary_restrictions: DietaryRestrictionsEnum[];
  /**
   * @minLength 1
   * @maxLength 40
   * @nullable
   */
  dietary_restrictions_other?: string | null;
  dietary_allergies: DietaryAllergiesEnum[];
  /**
   * @minLength 1
   * @maxLength 40
   * @nullable
   */
  dietary_allergies_other?: string | null;
  /**
   * @minLength 1
   * @maxLength 200
   * @nullable
   */
  additional_accommodations?: string | null;
  us_visa_support_is_required: boolean;
  /** @nullable */
  us_visa_letter_of_invitation_required?: boolean | null;
  /**
   * @minLength 1
   * @maxLength 200
   * @nullable
   */
  us_visa_support_full_name?: string | null;
  /**
   * @minLength 1
   * @maxLength 50
   * @nullable
   */
  us_visa_support_document_number?: string | null;
  /** @nullable */
  us_visa_support_national_identification_document_type?: AttendeeRSVPCreateRequestUsVisaSupportNationalIdentificationDocumentType;
  /** @nullable */
  us_visa_support_citizenship?: AttendeeRSVPCreateRequestUsVisaSupportCitizenship;
  /**
   * @minLength 1
   * @maxLength 500
   * @nullable
   */
  us_visa_support_address?: string | null;
  /**
   * Will you be under 18 on January 22, 2026
   * @nullable
   */
  under_18_by_date?: boolean | null;
  /** @nullable */
  parental_consent_form_signed?: boolean | null;
  agree_to_media_release?: boolean;
  agree_to_liability_release?: boolean;
  agree_to_rules_code_of_conduct?: boolean;
  /**
   * @minLength 1
   * @maxLength 200
   */
  emergency_contact_name: string;
  /**
   * @minLength 1
   * @maxLength 128
   */
  personal_phone_number: string;
  /**
   * @minLength 1
   * @maxLength 128
   */
  emergency_contact_phone_number: string;
  /**
   * @minLength 1
   * @maxLength 254
   */
  emergency_contact_email: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  emergency_contact_relationship: string;
  /** @nullable */
  special_interest_track_one?: AttendeeRSVPCreateRequestSpecialInterestTrackOne;
  /** @nullable */
  special_interest_track_two?: AttendeeRSVPCreateRequestSpecialInterestTrackTwo;
  /**
   * Do you already have an AR or VR app in any store? And if so, which store(s)?
   * @minLength 1
   * @maxLength 250
   * @nullable
   */
  app_in_store?: string | null;
  /**
   * @minLength 1
   * @maxLength 250
   * @nullable
   */
  currently_build_for_xr?: string | null;
  /**
   * @minLength 1
   * @maxLength 250
   * @nullable
   */
  currently_use_xr?: string | null;
  /**
   * @minLength 1
   * @maxLength 250
   * @nullable
   */
  non_xr_talents?: string | null;
  /**
   * @minLength 1
   * @maxLength 250
   * @nullable
   */
  ar_vr_ap_in_store?: string | null;
  reality_hack_project_to_product?: boolean;
  participation_class?: ParticipationClassEnum;
  /**
   * @minLength 1
   * @maxLength 100
   * @nullable
   */
  sponsor_company?: string | null;
  /**
   * @minLength 1
   * @maxLength 2000
   * @nullable
   */
  breakthrough_hacks_interest?: string | null;
  /** @nullable */
  loaner_headset_preference?: AttendeeRSVPCreateRequestLoanerHeadsetPreference;
}
