/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type AttendeepreferencesListPreference = typeof AttendeepreferencesListPreference[keyof typeof AttendeepreferencesListPreference];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AttendeepreferencesListPreference = {
  N: 'N',
  T: 'T',
  Y: 'Y',
} as const;
