/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { SkillProficiencyAttendee } from './skillProficiencyAttendee';
import type { FileUpload } from './fileUpload';
import type { Team } from './team';
import type { EventRsvpSummary } from './eventRsvpSummary';
import type { HardwareDeviceDetail } from './hardwareDeviceDetail';
import type { WorkshopAttendeeWorkshopDetail } from './workshopAttendeeWorkshopDetail';
import type { ParticipationClassEnum } from './participationClassEnum';
import type { DestinyHardwareEnum } from './destinyHardwareEnum';
import type { TrackEnum } from './trackEnum';
import type { EventTrack } from './eventTrack';
import type { EventDestinyHardware } from './eventDestinyHardware';

export interface AttendeeDetail {
  readonly id?: string;
  /** @maxLength 150 */
  first_name?: string;
  /** @maxLength 150 */
  last_name?: string;
  skill_proficiencies: SkillProficiencyAttendee[];
  profile_image: FileUpload;
  /** @maxLength 1000 */
  bio?: string;
  /** @nullable */
  checked_in_at?: string | null;
  team: Team;
  event_rsvp: EventRsvpSummary;
  hardware_devices: HardwareDeviceDetail[];
  /**
   * I.e., a Discord username
   * @maxLength 40
   * @nullable
   */
  communications_platform_username?: string | null;
  /** @maxLength 254 */
  email: string;
  workshops: WorkshopAttendeeWorkshopDetail[];
  participation_class?: ParticipationClassEnum;
  initial_setup?: boolean;
  prefers_destiny_hardware: DestinyHardwareEnum[];
  guardian_of?: string[];
  /** @nullable */
  sponsor_handler?: string | null;
  intended_tracks: TrackEnum[];
  intended_hardware_hack?: boolean;
  readonly intended_event_tracks?: readonly EventTrack[];
  readonly prefers_event_destiny_hardware?: readonly EventDestinyHardware[];
  readonly created_at?: string;
  readonly updated_at?: string;
}
