/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { AttendeeNameRequestParticipationRole } from './attendeeNameRequestParticipationRole';

export interface AttendeeNameRequest {
  /** @maxLength 150 */
  first_name?: string;
  /** @maxLength 150 */
  last_name?: string;
  /** @nullable */
  participation_role?: AttendeeNameRequestParticipationRole;
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
}
