/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { LoanerHeadsetPreferenceEnum } from './loanerHeadsetPreferenceEnum';

/**
 * @nullable
 */
export type AttendeeRSVPCreateRequestLoanerHeadsetPreference = LoanerHeadsetPreferenceEnum | null;
