/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type AttendeesListParticipationClass = typeof AttendeesListParticipationClass[keyof typeof AttendeesListParticipationClass];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AttendeesListParticipationClass = {
  E: 'E',
  G: 'G',
  J: 'J',
  M: 'M',
  O: 'O',
  P: 'P',
  S: 'S',
  V: 'V',
} as const;
