/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { AttendeeNameParticipationRole } from './attendeeNameParticipationRole';
import type { FileUpload } from './fileUpload';

export interface AttendeeName {
  readonly id?: string;
  /** @maxLength 150 */
  first_name?: string;
  /** @maxLength 150 */
  last_name?: string;
  /** @nullable */
  participation_role?: AttendeeNameParticipationRole;
  readonly profile_image?: FileUpload;
  /** @maxLength 254 */
  email: string;
}
