/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { DestinyHardwareEnum } from './destinyHardwareEnum';
import type { ParticipationClassEnum } from './participationClassEnum';
import type { TrackEnum } from './trackEnum';

export interface AttendeePatch {
  readonly id?: string;
  /** @maxLength 150 */
  first_name?: string;
  /** @maxLength 150 */
  last_name?: string;
  /**
   * @maxLength 36
   * @nullable
   */
  authentication_id?: string | null;
  /** @nullable */
  profile_image?: string | null;
  /** @maxLength 1000 */
  bio?: string;
  /** @nullable */
  checked_in_at?: string | null;
  prefers_destiny_hardware: DestinyHardwareEnum[];
  /**
   * I.e., a Discord username
   * @maxLength 40
   * @nullable
   */
  communications_platform_username?: string | null;
  /** @maxLength 254 */
  email: string;
  /**
   * @maxLength 100
   * @nullable
   */
  sponsor_company?: string | null;
  participation_class?: ParticipationClassEnum;
  initial_setup?: boolean;
  guardian_of?: string[];
  /** @nullable */
  sponsor_handler?: string | null;
  intended_tracks: TrackEnum[];
  intended_hardware_hack?: boolean;
  readonly created_at?: string;
  readonly updated_at?: string;
}
