/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { AuthSchemaRetrieveFormat } from './authSchemaRetrieveFormat';
import type { AuthSchemaRetrieveLang } from './authSchemaRetrieveLang';

export type AuthSchemaRetrieveParams = {
format?: AuthSchemaRetrieveFormat;
lang?: AuthSchemaRetrieveLang;
};
