/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `ST` - Stata
* `WK` - Walker
 */
export type BuildingEnum = typeof BuildingEnum[keyof typeof BuildingEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuildingEnum = {
  ST: 'ST',
  WK: 'WK',
} as const;
