/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `D` - Development
* `A` - Design
* `P` - Prototyping
* `M` - Project Management and Leadership
* `S` - Specialty
 */
export type CategoryEnum = typeof CategoryEnum[keyof typeof CategoryEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryEnum = {
  D: 'D',
  A: 'A',
  P: 'P',
  M: 'M',
  S: 'S',
} as const;
