/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { TableNumber } from './tableNumber';
import type { DestinyTeamUpdateTrack } from './destinyTeamUpdateTrack';
import type { DestinyHardwareEnum } from './destinyHardwareEnum';

export interface DestinyTeamUpdate {
  readonly id?: string;
  table: TableNumber;
  /** @nullable */
  track?: DestinyTeamUpdateTrack;
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  round: number;
  hardware_hack?: boolean;
  destiny_hardware?: DestinyHardwareEnum;
  readonly created_at?: string;
  readonly updated_at?: string;
  attendees?: string[];
}
