/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type DestinyteamattendeevibesListParams = {
attendee?: string;
destiny_team__round?: number;
/**
 * A search term.
 */
search?: string;
vibe?: number;
};
