/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `M` - Best MR Lifestyle App for Meta Quest
* `Q` - Best Lifestyle World with Meta Horizons Worlds
* `T` - Best use of Haptics
* `S` - Snap Spectacles Challenge
* `N` - Pioneering a Neuroadaptive Future
* `X` - Best Use of ShapesXR
* `Y` - Best use of STYLY
* `L` - Best use of Lambda AI Cloud Services
* `U` - Qualcomm IoT
* `V` - Best use of Apple Vision Pro
 */
export type DestinyHardwareEnum = typeof DestinyHardwareEnum[keyof typeof DestinyHardwareEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DestinyHardwareEnum = {
  M: 'M',
  Q: 'Q',
  T: 'T',
  S: 'S',
  N: 'N',
  X: 'X',
  Y: 'Y',
  L: 'L',
  U: 'U',
  V: 'V',
} as const;
