/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { TableNumberRequest } from './tableNumberRequest';
import type { DestinyTeamUpdateRequestTrack } from './destinyTeamUpdateRequestTrack';
import type { DestinyHardwareEnum } from './destinyHardwareEnum';

export interface DestinyTeamUpdateRequest {
  table: TableNumberRequest;
  /** @nullable */
  track?: DestinyTeamUpdateRequestTrack;
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  round: number;
  hardware_hack?: boolean;
  destiny_hardware?: DestinyHardwareEnum;
  attendees?: string[];
}
