/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface DestinyTeamAttendeeVibe {
  readonly id?: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  vibe: number;
  destiny_team: string;
  attendee: string;
}
