/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { AttendeeName } from './attendeeName';
import type { TableNumber } from './tableNumber';
import type { DestinyTeamTrack } from './destinyTeamTrack';
import type { DestinyHardwareEnum } from './destinyHardwareEnum';

/**
 * Base serializer that automatically scopes foreign key fields to the current event.

This serializer ensures that when validating foreign key relationships,
only objects from the current event are considered valid. This is crucial
for maintaining proper event isolation in the multi-tenant system.

Usage:
    class MySerializer(EventScopedSerializer):
        class Meta:
            model = MyModel
            fields = ['id', 'name', 'foreign_key_field']
 */
export interface DestinyTeam {
  readonly id?: string;
  attendees: AttendeeName[];
  table: TableNumber;
  /** @nullable */
  track?: DestinyTeamTrack;
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  round: number;
  hardware_hack?: boolean;
  destiny_hardware?: DestinyHardwareEnum;
  readonly created_at?: string;
  readonly updated_at?: string;
  event: string;
}
