/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { TrackEnum } from './trackEnum';

/**
 * @nullable
 */
export type DestinyTeamTrack = TrackEnum | null;
