/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type DestinyteamsListTrack = typeof DestinyteamsListTrack[keyof typeof DestinyteamsListTrack] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DestinyteamsListTrack = {
  A: 'A',
  C: 'C',
  D: 'D',
  E: 'E',
  H: 'H',
  L: 'L',
  S: 'S',
} as const;
