/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { DestinyteamsListTrack } from './destinyteamsListTrack';

export type DestinyteamsListParams = {
attendees?: string[];
round?: number;
/**
 * A search term.
 */
search?: string;
table__number?: number;
/**
 * * `C` - Open Lab (AKA Community Hack)
* `S` - Connecting for Change with Social XR
* `E` - Augmented Design & Engineering
* `D` - Standing on the Shoulders of Sustainability
* `A` - AeroSpatial Exploration
* `L` - Augmented Intelligence
* `H` - Healthcare
 */
track?: DestinyteamsListTrack;
};
