/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `1` - Nut allergy
* `2` - Shellfish allergy
* `3` - Dairy allergy
* `4` - Soy allergy
* `5` - Other
 */
export type DietaryAllergiesEnum = typeof DietaryAllergiesEnum[keyof typeof DietaryAllergiesEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DietaryAllergiesEnum = {
  NUMBER_1: '1',
  NUMBER_2: '2',
  NUMBER_3: '3',
  NUMBER_4: '4',
  NUMBER_5: '5',
} as const;
