/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `1` - Vegetarian
* `2` - Vegan
* `3` - Gluten free
* `4` - Halal
* `5` - Lactose Intolerant
* `6` - Kosher
* `7` - Other
 */
export type DietaryRestrictionsEnum = typeof DietaryRestrictionsEnum[keyof typeof DietaryRestrictionsEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DietaryRestrictionsEnum = {
  NUMBER_1: '1',
  NUMBER_2: '2',
  NUMBER_3: '3',
  NUMBER_4: '4',
  NUMBER_5: '5',
  NUMBER_6: '6',
  NUMBER_7: '7',
} as const;
