/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `A` - Digital Art
* `B` - Animation
* `C` - Sound
* `D` - UX and UI
* `E` - Video
* `F` - Other
 */
export type DigitalDesignerSkillsEnum = typeof DigitalDesignerSkillsEnum[keyof typeof DigitalDesignerSkillsEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DigitalDesignerSkillsEnum = {
  A: 'A',
  B: 'B',
  C: 'C',
  D: 'D',
  E: 'E',
  F: 'F',
} as const;
