/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `A` - Yes
* `B` - No
* `C` - I prefer not to say
 */
export type DisabilityIdentityEnum = typeof DisabilityIdentityEnum[keyof typeof DisabilityIdentityEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DisabilityIdentityEnum = {
  A: 'A',
  B: 'B',
  C: 'C',
} as const;
