/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { DiscordUsernameRoleParticipationRole } from './discordUsernameRoleParticipationRole';
import type { ParticipationClassEnum } from './participationClassEnum';

export interface DiscordUsernameRole {
  /**
   * I.e., a Discord username
   * @maxLength 40
   * @nullable
   */
  communications_platform_username?: string | null;
  /** @nullable */
  participation_role?: DiscordUsernameRoleParticipationRole;
  participation_class?: ParticipationClassEnum;
}
