/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface Event {
  readonly id?: string;
  /** @maxLength 100 */
  name: string;
  start_date: string;
  end_date: string;
  /** Only one event should be active at a time */
  is_active?: boolean;
  readonly created_at?: string;
  readonly updated_at?: string;
}
