/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { CountryEnum } from './countryEnum';

/**
 * @nullable
 */
export type EventRsvpRequestUsVisaSupportCitizenship = CountryEnum | null;
