/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface EventTrack {
  readonly id?: string;
  /**
   * Six char code
   * @maxLength 6
   */
  code: string;
  /** @maxLength 100 */
  name: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  order?: number;
  sponsor_companies?: string[];
}
