/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * Minimal attendee data needed for team attendee picker dropdowns.
 */
export interface EventRsvpAttendeeOption {
  id: string;
  first_name: string;
  last_name: string;
  /** @nullable */
  checked_in_at: string | null;
}
