/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { EventRsvpSummaryShirtSize } from './eventRsvpSummaryShirtSize';
import type { ParticipationClassEnum } from './participationClassEnum';

/**
 * Base serializer that automatically scopes foreign key fields to the current event.

This serializer ensures that when validating foreign key relationships,
only objects from the current event are considered valid. This is crucial
for maintaining proper event isolation in the multi-tenant system.

Usage:
    class MySerializer(EventScopedSerializer):
        class Meta:
            model = MyModel
            fields = ['id', 'name', 'foreign_key_field']
 */
export interface EventRsvpSummary {
  readonly id?: string;
  event: string;
  /** @nullable */
  shirt_size?: EventRsvpSummaryShirtSize;
  /** @nullable */
  checked_in_at?: string | null;
  /**
   * I.e., a Discord username
   * @maxLength 40
   * @nullable
   */
  communication_platform_username?: string | null;
  participation_class?: ParticipationClassEnum;
  /**
   * @maxLength 100
   * @nullable
   */
  sponsor_company?: string | null;
}
