/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `A` - Application
* `R` - RSVP
 */
export type FormTypeEnum = typeof FormTypeEnum[keyof typeof FormTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FormTypeEnum = {
  A: 'A',
  R: 'R',
} as const;
