/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `A` - Cisgender female
* `B` - Cisgender male
* `C` - Transgender female
* `D` - Transgender male
* `E` - Gender non-conforming, non-binary, or gender queer
* `F` - Two-spirit
* `G` - I prefer not to say
* `O` - Other
 */
export type GenderIdentityEnum = typeof GenderIdentityEnum[keyof typeof GenderIdentityEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GenderIdentityEnum = {
  A: 'A',
  B: 'B',
  C: 'C',
  D: 'D',
  E: 'E',
  F: 'F',
  G: 'G',
  O: 'O',
} as const;
