/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface GroupDetail {
  readonly id?: number;
  /** @maxLength 150 */
  name: string;
  permissions?: number[];
}
