/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `A` - 3D Printing
* `B` - Soldering
* `C` - Circuits
* `D` - Arduino
* `E` - ESP32
* `F` - Unity
* `G` - Physical Prototyping
* `H` - I have no prior experience
* `O` - Other
 */
export type HardwareHackDetailEnum = typeof HardwareHackDetailEnum[keyof typeof HardwareHackDetailEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HardwareHackDetailEnum = {
  A: 'A',
  B: 'B',
  C: 'C',
  D: 'D',
  E: 'E',
  F: 'F',
  G: 'G',
  H: 'H',
  O: 'O',
} as const;
