/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type HardwaredevicesListHardwareRelatesToDestinyHardware = typeof HardwaredevicesListHardwareRelatesToDestinyHardware[keyof typeof HardwaredevicesListHardwareRelatesToDestinyHardware] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HardwaredevicesListHardwareRelatesToDestinyHardware = {
  L: 'L',
  M: 'M',
  N: 'N',
  Q: 'Q',
  S: 'S',
  T: 'T',
  U: 'U',
  V: 'V',
  X: 'X',
  Y: 'Y',
} as const;
