/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { HardwareRequestRequesterRequest } from './hardwareRequestRequesterRequest';
import type { TeamRequest } from './teamRequest';
import type { HardwareRequestStatusEnum } from './hardwareRequestStatusEnum';

export interface HardwareRequestListRequest {
  hardware: string;
  /** @nullable */
  hardware_device?: string | null;
  requester: HardwareRequestRequesterRequest;
  team: TeamRequest;
  /** @maxLength 1000 */
  reason?: string;
  status?: HardwareRequestStatusEnum;
}
