/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `A` - Not at all interested; I'll pass
* `B` - Some mild interest
* `C` - Most likely
* `D` - 100%; I want to join
 */
export type HardwareHackInterestEnum = typeof HardwareHackInterestEnum[keyof typeof HardwareHackInterestEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HardwareHackInterestEnum = {
  A: 'A',
  B: 'B',
  C: 'C',
  D: 'D',
} as const;
