/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { HardwareDeviceHardware } from './hardwareDeviceHardware';
import type { HardwareRequest } from './hardwareRequest';

export interface HardwareDeviceDetail {
  readonly id?: string;
  readonly hardware?: HardwareDeviceHardware;
  /** @maxLength 100 */
  serial: string;
  readonly checked_out_to?: HardwareRequest;
  readonly created_at?: string;
  readonly updated_at?: string;
}
