/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { HardwareListRelatesToDestinyHardware } from './hardwareListRelatesToDestinyHardware';
import type { HardwareListTags } from './hardwareListTags';

export type HardwareListParams = {
/**
 * * `M` - Best MR Lifestyle App for Meta Quest
* `Q` - Best Lifestyle World with Meta Horizons Worlds
* `T` - Best use of Haptics
* `S` - Snap Spectacles Challenge
* `N` - Pioneering a Neuroadaptive Future
* `X` - Best Use of ShapesXR
* `Y` - Best use of STYLY
* `L` - Best use of Lambda AI Cloud Services
* `U` - Qualcomm IoT
* `V` - Best use of Apple Vision Pro
 */
relates_to_destiny_hardware?: HardwareListRelatesToDestinyHardware;
/**
 * A search term.
 */
search?: string;
/**
 * * `AC` - Accessory
* `SE` - Sensor
* `VR` - Virtual Reality
* `AR` - Augmented Reality
* `MR` - Mixed Reality
* `CO` - Computer
* `HA` - Haptics
* `CA` - Camera
* `TA` - Tablet
* `HD` - Holographic Display
 */
tags?: HardwareListTags;
};
