/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { FileUpload } from './fileUpload';
import type { TagsEnum } from './tagsEnum';

export interface HardwareCount {
  readonly id?: string;
  /** @maxLength 50 */
  name: string;
  /** @maxLength 1000 */
  description?: string;
  image: FileUpload;
  available: number;
  checked_out: number;
  total: number;
  readonly created_at?: string;
  readonly updated_at?: string;
  tags: TagsEnum[];
}
