/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface HardwareDeviceHistoryRequest {
  /** @nullable */
  hardware?: string | null;
  /**
   * @minLength 1
   * @maxLength 100
   */
  serial: string;
  /** @nullable */
  checked_out_to?: string | null;
}
