/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { FileUpload } from './fileUpload';
import type { TagsEnum } from './tagsEnum';
import type { HardwareRelatesToDestinyHardware } from './hardwareRelatesToDestinyHardware';

export interface Hardware {
  readonly id?: string;
  /** @maxLength 50 */
  name: string;
  /** @maxLength 1000 */
  description?: string;
  image: FileUpload;
  tags: TagsEnum[];
  /** @nullable */
  relates_to_destiny_hardware?: HardwareRelatesToDestinyHardware;
  readonly created_at?: string;
  readonly updated_at?: string;
}
