/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { HardwareDeviceHardwareTags } from './hardwareDeviceHardwareTags';

export interface HardwareDeviceHardware {
  readonly id?: string;
  /** @maxLength 50 */
  name: string;
  /** @nullable */
  tags?: HardwareDeviceHardwareTags;
  /** @nullable */
  sponsor_company?: string | null;
}
