/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `P` - Pending
* `A` - Approved
* `R` - Rejected
* `C` - Checked out
 */
export type HardwareRequestStatusEnum = typeof HardwareRequestStatusEnum[keyof typeof HardwareRequestStatusEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HardwareRequestStatusEnum = {
  P: 'P',
  A: 'A',
  R: 'R',
  C: 'C',
} as const;
