/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type HardwareListTags = typeof HardwareListTags[keyof typeof HardwareListTags] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HardwareListTags = {
  AC: 'AC',
  AR: 'AR',
  CA: 'CA',
  CO: 'CO',
  HA: 'HA',
  HD: 'HD',
  MR: 'MR',
  SE: 'SE',
  TA: 'TA',
  VR: 'VR',
} as const;
