/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type HardwarerequestsListParams = {
hardware?: string;
requester__first_name?: string;
requester__id?: string;
requester__last_name?: string;
/**
 * A search term.
 */
search?: string;
team?: string;
};
