/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { TagsEnum } from './tagsEnum';
import type { HardwareCreateRequestRelatesToDestinyHardware } from './hardwareCreateRequestRelatesToDestinyHardware';

export interface HardwareCreateRequest {
  /**
   * @minLength 1
   * @maxLength 50
   */
  name: string;
  /** @maxLength 1000 */
  description?: string;
  /** @nullable */
  image?: string | null;
  tags: TagsEnum[];
  /** @nullable */
  relates_to_destiny_hardware?: HardwareCreateRequestRelatesToDestinyHardware;
}
