/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { HardwareRequestStatusEnum } from './hardwareRequestStatusEnum';

export interface HardwareRequestCreate {
  readonly id?: string;
  hardware: string;
  /** @nullable */
  hardware_device?: string | null;
  requester: string;
  /** @nullable */
  team?: string | null;
  /** @maxLength 1000 */
  reason?: string;
  status?: HardwareRequestStatusEnum;
  readonly created_at?: string;
  readonly updated_at?: string;
}
