/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { HardwareCount } from './hardwareCount';
import type { HardwareDeviceDetail } from './hardwareDeviceDetail';
import type { Attendee } from './attendee';
import type { Team } from './team';
import type { HardwareRequestStatusEnum } from './hardwareRequestStatusEnum';

export interface HardwareRequestDetail {
  readonly id?: string;
  readonly hardware?: HardwareCount;
  readonly hardware_device?: HardwareDeviceDetail;
  readonly requester?: Attendee;
  team: Team;
  /** @maxLength 1000 */
  reason?: string;
  status?: HardwareRequestStatusEnum;
  readonly created_at?: string;
  readonly updated_at?: string;
}
