/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { TagsEnum } from './tagsEnum';

/**
 * @nullable
 */
export type HardwareDeviceHardwareTags = TagsEnum | null;
