/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { FileUpload } from './fileUpload';
import type { HardwareCountDetailRelatesToDestinyHardware } from './hardwareCountDetailRelatesToDestinyHardware';
import type { HardwareDeviceHardwareCountDetail } from './hardwareDeviceHardwareCountDetail';
import type { TagsEnum } from './tagsEnum';

export interface HardwareCountDetail {
  readonly id?: string;
  /** @maxLength 50 */
  name: string;
  /** @maxLength 1000 */
  description?: string;
  image: FileUpload;
  /** @nullable */
  relates_to_destiny_hardware?: HardwareCountDetailRelatesToDestinyHardware;
  readonly relates_to_event_destiny_hardware?: string;
  available: number;
  checked_out: number;
  total: number;
  readonly created_at?: string;
  readonly updated_at?: string;
  hardware_devices: HardwareDeviceHardwareCountDetail[];
  tags: TagsEnum[];
}
