/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { HardwareRequestStatusEnum } from './hardwareRequestStatusEnum';

export interface HardwareRequestCreateRequest {
  hardware: string;
  /** @nullable */
  hardware_device?: string | null;
  /** @minLength 1 */
  requester: string;
  /** @nullable */
  team?: string | null;
  /** @maxLength 1000 */
  reason?: string;
  status?: HardwareRequestStatusEnum;
}
