/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface HardwareDeviceHistory {
  readonly history_id?: number;
  readonly id?: string;
  /** @nullable */
  hardware?: string | null;
  /** @maxLength 100 */
  serial: string;
  /** @nullable */
  checked_out_to?: string | null;
  readonly created_at?: string;
  readonly updated_at?: string;
}
