/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { HardwaredevicesListHardwareRelatesToDestinyHardware } from './hardwaredevicesListHardwareRelatesToDestinyHardware';

export type HardwaredevicesListParams = {
checked_out_to?: string;
hardware?: string;
/**
 * * `M` - Best MR Lifestyle App for Meta Quest
* `Q` - Best Lifestyle World with Meta Horizons Worlds
* `T` - Best use of Haptics
* `S` - Snap Spectacles Challenge
* `N` - Pioneering a Neuroadaptive Future
* `X` - Best Use of ShapesXR
* `Y` - Best use of STYLY
* `L` - Best use of Lambda AI Cloud Services
* `U` - Qualcomm IoT
* `V` - Best use of Apple Vision Pro
 */
hardware__relates_to_destiny_hardware?: HardwaredevicesListHardwareRelatesToDestinyHardware;
/**
 * A search term.
 */
search?: string;
serial?: string;
};
