/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type HardwaredevicehistoryListParams = {
checked_out_to?: string;
hardware?: string;
id?: string;
/**
 * A search term.
 */
search?: string;
serial?: string;
};
