/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { HardwareRequestRequester } from './hardwareRequestRequester';
import type { Team } from './team';
import type { HardwareRequestStatusEnum } from './hardwareRequestStatusEnum';

export interface HardwareRequestList {
  readonly id?: string;
  hardware: string;
  /** @nullable */
  hardware_device?: string | null;
  requester: HardwareRequestRequester;
  team: Team;
  /** @maxLength 1000 */
  reason?: string;
  status?: HardwareRequestStatusEnum;
  readonly created_at?: string;
  readonly updated_at?: string;
}
