/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { DestinyHardwareEnum } from './destinyHardwareEnum';

/**
 * @nullable
 */
export type HardwareCountRelatesToDestinyHardware = DestinyHardwareEnum | null;
