/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type HardwarerequestsListStatus = typeof HardwarerequestsListStatus[keyof typeof HardwarerequestsListStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HardwarerequestsListStatus = {
  A: 'A',
  C: 'C',
  P: 'P',
  R: 'R',
} as const;
