/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `F` - A friend
* `V` - A Reality Hack organizer or volunteer
* `N` - A teacher or someone in my professional network
* `S` - Social media
* `C` - Campus poster or ad
* `P` - I participated in the MIT XR Hackathon before
* `O` - Other
 */
export type HeardAboutUsEnum = typeof HeardAboutUsEnum[keyof typeof HeardAboutUsEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HeardAboutUsEnum = {
  F: 'F',
  V: 'V',
  N: 'N',
  S: 'S',
  C: 'C',
  P: 'P',
  O: 'O',
} as const;
