/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { HelpRequestTeamLocation } from './helpRequestTeamLocation';

export interface HelpRequestTable {
  readonly id?: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  number: number;
  location: HelpRequestTeamLocation;
}
