/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { HelpRequestTable } from './helpRequestTable';

export interface HelpRequestTeam {
  readonly id?: string;
  /** @maxLength 50 */
  name: string;
  table: HelpRequestTable;
}
