/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `+` - Created
* `~` - Changed
* `-` - Deleted
 */
export type HistoryTypeEnum = typeof HistoryTypeEnum[keyof typeof HistoryTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HistoryTypeEnum = {
  '+': '+',
  '~': '~',
  '-': '-',
} as const;
