/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `Industry` - Industry
* `Accounting ` - Accounting 
* `Airlines/Aviation` - Airlines/Aviation
* `Alternative Dispute Resolution` - Alternative Dispute Resolution
* `Alternative Medicine` - Alternative Medicine
* `Animation` - Animation
* `Apparel/Fashion` - Apparel/Fashion
* `Architecture/Planning` - Architecture/Planning
* `Arts/Crafts` - Arts/Crafts
* `Automotive` - Automotive
* `Aviation/Aerospace` - Aviation/Aerospace
* `Banking/Mortgage` - Banking/Mortgage
* `Biotechnology/Greentech` - Biotechnology/Greentech
* `Broadcast Media` - Broadcast Media
* `Building Materials` - Building Materials
* `Business Supplies/Equipment` - Business Supplies/Equipment
* `Capital Markets/Hedge Fund/Private Equity` - Capital Markets/Hedge Fund/Private Equity
* `Chemicals` - Chemicals
* `Civic/Social Organization` - Civic/Social Organization
* `Civil Engineering` - Civil Engineering
* `Commercial Real Estate` - Commercial Real Estate
* `Computer Games` - Computer Games
* `Computer Hardware` - Computer Hardware
* `Computer Networking` - Computer Networking
* `Computer Software/Engineering` - Computer Software/Engineering
* `Computer/Network Security` - Computer/Network Security
* `Construction` - Construction
* `Consumer Electronics` - Consumer Electronics
* `Consumer Goods` - Consumer Goods
* `Consumer Services` - Consumer Services
* `Cosmetics` - Cosmetics
* `Dairy` - Dairy
* `Defense/Space` - Defense/Space
* `Design` - Design
* `E-Learning` - E-Learning
* `Education Management` - Education Management
* `Electrical/Electronic Manufacturing` - Electrical/Electronic Manufacturing
* `Entertainment/Movie Production` - Entertainment/Movie Production
* `Environmental Services` - Environmental Services
* `Events Services` - Events Services
* `Executive Office` - Executive Office
* `Facilities Services` - Facilities Services
* `Farming` - Farming
* `Financial Services` - Financial Services
* `Fine Art` - Fine Art
* `Fishery` - Fishery
* `Food Production` - Food Production
* `Food/Beverages` - Food/Beverages
* `Fundraising` - Fundraising
* `Furniture` - Furniture
* `Gambling/Casinos` - Gambling/Casinos
* `Glass/Ceramics/Concrete` - Glass/Ceramics/Concrete
* `Government Administration` - Government Administration
* `Government Relations` - Government Relations
* `Graphic Design/Web Design` - Graphic Design/Web Design
* `Health/Fitness` - Health/Fitness
* `Higher Education/Acadamia` - Higher Education/Acadamia
* `Hospital/Health Care` - Hospital/Health Care
* `Hospitality` - Hospitality
* `Human Resources/HR` - Human Resources/HR
* `Import/Export` - Import/Export
* `Individual/Family Services` - Individual/Family Services
* `Industrial Automation` - Industrial Automation
* `Information Services` - Information Services
* `Information Technology/IT` - Information Technology/IT
* `Insurance` - Insurance
* `International Affairs` - International Affairs
* `International Trade/Development` - International Trade/Development
* `Internet` - Internet
* `Investment Banking/Venture` - Investment Banking/Venture
* `Investment Management/Hedge Fund/Private Equity` - Investment Management/Hedge Fund/Private Equity
* `Judiciary` - Judiciary
* `Law Enforcement` - Law Enforcement
* `Law Practice/Law Firms` - Law Practice/Law Firms
* `Legal Services` - Legal Services
* `Legislative Office` - Legislative Office
* `Leisure/Travel` - Leisure/Travel
* `Library` - Library
* `Logistics/Procurement` - Logistics/Procurement
* `Luxury Goods/Jewelry` - Luxury Goods/Jewelry
* `Machinery` - Machinery
* `Management Consulting` - Management Consulting
* `Maritime` - Maritime
* `Market Research` - Market Research
* `Marketing/Advertising/Sales` - Marketing/Advertising/Sales
* `Mechanical or Industrial Engineering` - Mechanical or Industrial Engineering
* `Media Production` - Media Production
* `Medical Equipment` - Medical Equipment
* `Medical Practice` - Medical Practice
* `Mental Health Care` - Mental Health Care
* `Military Industry` - Military Industry
* `Mining/Metals` - Mining/Metals
* `Motion Pictures/Film` - Motion Pictures/Film
* `Museums/Institutions` - Museums/Institutions
* `Music` - Music
* `Nanotechnology` - Nanotechnology
* `Newspapers/Journalism` - Newspapers/Journalism
* `Non-Profit/Volunteering` - Non-Profit/Volunteering
* `Oil/Energy/Solar/Greentech` - Oil/Energy/Solar/Greentech
* `Online Publishing` - Online Publishing
* `Outsourcing/Offshoring` - Outsourcing/Offshoring
* `Package/Freight Delivery` - Package/Freight Delivery
* `Packaging/Containers` - Packaging/Containers
* `Paper/Forest Products` - Paper/Forest Products
* `Performing Arts` - Performing Arts
* `Pharmaceuticals` - Pharmaceuticals
* `Philanthropy` - Philanthropy
* `Photography` - Photography
* `Plastics` - Plastics
* `Political Organization` - Political Organization
* `Primary/Secondary Education` - Primary/Secondary Education
* `Printing` - Printing
* `Professional Training` - Professional Training
* `Program Development` - Program Development
* `Public Relations/PR` - Public Relations/PR
* `Public Safety` - Public Safety
* `Publishing Industry` - Publishing Industry
* `Railroad Manufacture` - Railroad Manufacture
* `Ranching` - Ranching
* `Real Estate/Mortgage` - Real Estate/Mortgage
* `Recreational Facilities/Services` - Recreational Facilities/Services
* `Religious Institutions` - Religious Institutions
* `Renewables/Environment` - Renewables/Environment
* `Research Industry` - Research Industry
* `Restaurants` - Restaurants
* `Retail Industry` - Retail Industry
* `Security/Investigations` - Security/Investigations
* `Semiconductors` - Semiconductors
* `Shipbuilding` - Shipbuilding
* `Sporting Goods` - Sporting Goods
* `Sports` - Sports
* `Staffing/Recruiting` - Staffing/Recruiting
* `Supermarkets` - Supermarkets
* `Telecommunications` - Telecommunications
* `Textiles` - Textiles
* `Think Tanks` - Think Tanks
* `Tobacco` - Tobacco
* `Translation/Localization` - Translation/Localization
* `Transportation` - Transportation
* `Utilities` - Utilities
* `Venture Capital/VC` - Venture Capital/VC
* `Veterinary` - Veterinary
* `Warehousing` - Warehousing
* `Wholesale` - Wholesale
* `Wine/Spirits` - Wine/Spirits
* `Wireless` - Wireless
* `Writing/Editing` - Writing/Editing
* `Other` - Other
 */
export type IndustryEnum = typeof IndustryEnum[keyof typeof IndustryEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndustryEnum = {
  Industry: 'Industry',
  Accounting_: 'Accounting ',
  'Airlines/Aviation': 'Airlines/Aviation',
  Alternative_Dispute_Resolution: 'Alternative Dispute Resolution',
  Alternative_Medicine: 'Alternative Medicine',
  Animation: 'Animation',
  'Apparel/Fashion': 'Apparel/Fashion',
  'Architecture/Planning': 'Architecture/Planning',
  'Arts/Crafts': 'Arts/Crafts',
  Automotive: 'Automotive',
  'Aviation/Aerospace': 'Aviation/Aerospace',
  'Banking/Mortgage': 'Banking/Mortgage',
  'Biotechnology/Greentech': 'Biotechnology/Greentech',
  Broadcast_Media: 'Broadcast Media',
  Building_Materials: 'Building Materials',
  'Business_Supplies/Equipment': 'Business Supplies/Equipment',
  'Capital_Markets/Hedge_Fund/Private_Equity': 'Capital Markets/Hedge Fund/Private Equity',
  Chemicals: 'Chemicals',
  'Civic/Social_Organization': 'Civic/Social Organization',
  Civil_Engineering: 'Civil Engineering',
  Commercial_Real_Estate: 'Commercial Real Estate',
  Computer_Games: 'Computer Games',
  Computer_Hardware: 'Computer Hardware',
  Computer_Networking: 'Computer Networking',
  'Computer_Software/Engineering': 'Computer Software/Engineering',
  'Computer/Network_Security': 'Computer/Network Security',
  Construction: 'Construction',
  Consumer_Electronics: 'Consumer Electronics',
  Consumer_Goods: 'Consumer Goods',
  Consumer_Services: 'Consumer Services',
  Cosmetics: 'Cosmetics',
  Dairy: 'Dairy',
  'Defense/Space': 'Defense/Space',
  Design: 'Design',
  'E-Learning': 'E-Learning',
  Education_Management: 'Education Management',
  'Electrical/Electronic_Manufacturing': 'Electrical/Electronic Manufacturing',
  'Entertainment/Movie_Production': 'Entertainment/Movie Production',
  Environmental_Services: 'Environmental Services',
  Events_Services: 'Events Services',
  Executive_Office: 'Executive Office',
  Facilities_Services: 'Facilities Services',
  Farming: 'Farming',
  Financial_Services: 'Financial Services',
  Fine_Art: 'Fine Art',
  Fishery: 'Fishery',
  Food_Production: 'Food Production',
  'Food/Beverages': 'Food/Beverages',
  Fundraising: 'Fundraising',
  Furniture: 'Furniture',
  'Gambling/Casinos': 'Gambling/Casinos',
  'Glass/Ceramics/Concrete': 'Glass/Ceramics/Concrete',
  Government_Administration: 'Government Administration',
  Government_Relations: 'Government Relations',
  'Graphic_Design/Web_Design': 'Graphic Design/Web Design',
  'Health/Fitness': 'Health/Fitness',
  'Higher_Education/Acadamia': 'Higher Education/Acadamia',
  'Hospital/Health_Care': 'Hospital/Health Care',
  Hospitality: 'Hospitality',
  'Human_Resources/HR': 'Human Resources/HR',
  'Import/Export': 'Import/Export',
  'Individual/Family_Services': 'Individual/Family Services',
  Industrial_Automation: 'Industrial Automation',
  Information_Services: 'Information Services',
  'Information_Technology/IT': 'Information Technology/IT',
  Insurance: 'Insurance',
  International_Affairs: 'International Affairs',
  'International_Trade/Development': 'International Trade/Development',
  Internet: 'Internet',
  'Investment_Banking/Venture': 'Investment Banking/Venture',
  'Investment_Management/Hedge_Fund/Private_Equity': 'Investment Management/Hedge Fund/Private Equity',
  Judiciary: 'Judiciary',
  Law_Enforcement: 'Law Enforcement',
  'Law_Practice/Law_Firms': 'Law Practice/Law Firms',
  Legal_Services: 'Legal Services',
  Legislative_Office: 'Legislative Office',
  'Leisure/Travel': 'Leisure/Travel',
  Library: 'Library',
  'Logistics/Procurement': 'Logistics/Procurement',
  'Luxury_Goods/Jewelry': 'Luxury Goods/Jewelry',
  Machinery: 'Machinery',
  Management_Consulting: 'Management Consulting',
  Maritime: 'Maritime',
  Market_Research: 'Market Research',
  'Marketing/Advertising/Sales': 'Marketing/Advertising/Sales',
  Mechanical_or_Industrial_Engineering: 'Mechanical or Industrial Engineering',
  Media_Production: 'Media Production',
  Medical_Equipment: 'Medical Equipment',
  Medical_Practice: 'Medical Practice',
  Mental_Health_Care: 'Mental Health Care',
  Military_Industry: 'Military Industry',
  'Mining/Metals': 'Mining/Metals',
  'Motion_Pictures/Film': 'Motion Pictures/Film',
  'Museums/Institutions': 'Museums/Institutions',
  Music: 'Music',
  Nanotechnology: 'Nanotechnology',
  'Newspapers/Journalism': 'Newspapers/Journalism',
  'Non-Profit/Volunteering': 'Non-Profit/Volunteering',
  'Oil/Energy/Solar/Greentech': 'Oil/Energy/Solar/Greentech',
  Online_Publishing: 'Online Publishing',
  'Outsourcing/Offshoring': 'Outsourcing/Offshoring',
  'Package/Freight_Delivery': 'Package/Freight Delivery',
  'Packaging/Containers': 'Packaging/Containers',
  'Paper/Forest_Products': 'Paper/Forest Products',
  Performing_Arts: 'Performing Arts',
  Pharmaceuticals: 'Pharmaceuticals',
  Philanthropy: 'Philanthropy',
  Photography: 'Photography',
  Plastics: 'Plastics',
  Political_Organization: 'Political Organization',
  'Primary/Secondary_Education': 'Primary/Secondary Education',
  Printing: 'Printing',
  Professional_Training: 'Professional Training',
  Program_Development: 'Program Development',
  'Public_Relations/PR': 'Public Relations/PR',
  Public_Safety: 'Public Safety',
  Publishing_Industry: 'Publishing Industry',
  Railroad_Manufacture: 'Railroad Manufacture',
  Ranching: 'Ranching',
  'Real_Estate/Mortgage': 'Real Estate/Mortgage',
  'Recreational_Facilities/Services': 'Recreational Facilities/Services',
  Religious_Institutions: 'Religious Institutions',
  'Renewables/Environment': 'Renewables/Environment',
  Research_Industry: 'Research Industry',
  Restaurants: 'Restaurants',
  Retail_Industry: 'Retail Industry',
  'Security/Investigations': 'Security/Investigations',
  Semiconductors: 'Semiconductors',
  Shipbuilding: 'Shipbuilding',
  Sporting_Goods: 'Sporting Goods',
  Sports: 'Sports',
  'Staffing/Recruiting': 'Staffing/Recruiting',
  Supermarkets: 'Supermarkets',
  Telecommunications: 'Telecommunications',
  Textiles: 'Textiles',
  Think_Tanks: 'Think Tanks',
  Tobacco: 'Tobacco',
  'Translation/Localization': 'Translation/Localization',
  Transportation: 'Transportation',
  Utilities: 'Utilities',
  'Venture_Capital/VC': 'Venture Capital/VC',
  Veterinary: 'Veterinary',
  Warehousing: 'Warehousing',
  Wholesale: 'Wholesale',
  'Wine/Spirits': 'Wine/Spirits',
  Wireless: 'Wireless',
  'Writing/Editing': 'Writing/Editing',
  Other: 'Other',
} as const;
