/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { MentorHelpRequestStatusEnum } from './mentorHelpRequestStatusEnum';
import type { AnnouncementPendingEnum } from './announcementPendingEnum';

export interface LightHouseRequest {
  table: number;
  /** @minLength 1 */
  ip_address: string;
  mentor_requested?: MentorHelpRequestStatusEnum;
  announcement_pending?: AnnouncementPendingEnum;
}
