/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `META` - Meta Quest 3
* `SNAP` - Snap Spectacles
* `BYOD` - I am bringing my own XR device to work with.
* `HWHACK` - I've chosen the Hardware Hack, so I will probably not need a headset.
* `TBD` - I'm not sure yet
 */
export type LoanerHeadsetPreferenceEnum = typeof LoanerHeadsetPreferenceEnum[keyof typeof LoanerHeadsetPreferenceEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoanerHeadsetPreferenceEnum = {
  META: 'META',
  SNAP: 'SNAP',
  BYOD: 'BYOD',
  HWHACK: 'HWHACK',
  TBD: 'TBD',
} as const;
