/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { BuildingEnum } from './buildingEnum';
import type { RoomEnum } from './roomEnum';

export interface Location {
  readonly id?: string;
  building?: BuildingEnum;
  room?: RoomEnum;
  readonly created_at?: string;
  readonly updated_at?: string;
}
