/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { MentorhelprequestsListStatus } from './mentorhelprequestsListStatus';

export type MentorhelprequestsListParams = {
mentor?: string;
reporter?: string;
/**
 * A search term.
 */
search?: string;
/**
 * * `R` - Requested
* `A` - Acknowledged
* `E` - En Route
* `F` - Resolved
 */
status?: MentorhelprequestsListStatus;
team?: string;
team__table__number?: number;
};
