/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { MentorHelpRequestHistoryCategory } from './mentorHelpRequestHistoryCategory';
import type { TopicEnum } from './topicEnum';
import type { MentorHelpRequestStatusEnum } from './mentorHelpRequestStatusEnum';

export interface MentorHelpRequestHistory {
  readonly history_id?: number;
  readonly id?: string;
  /**
   * @maxLength 250
   * @nullable
   */
  title?: string | null;
  /**
   * @maxLength 2000
   * @nullable
   */
  description?: string | null;
  /** @nullable */
  team?: string | null;
  /** @nullable */
  category?: MentorHelpRequestHistoryCategory;
  topic: TopicEnum[];
  /** @nullable */
  reporter?: string | null;
  /** @nullable */
  mentor?: string | null;
  status?: MentorHelpRequestStatusEnum;
  /**
   * @maxLength 100
   * @nullable
   */
  category_specialty?: string | null;
  /**
   * @maxLength 50
   * @nullable
   */
  topic_other?: string | null;
  readonly created_at?: string;
  readonly updated_at?: string;
}
