/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { MentorHelpRequestHistoryRequestCategory } from './mentorHelpRequestHistoryRequestCategory';
import type { TopicEnum } from './topicEnum';
import type { MentorHelpRequestStatusEnum } from './mentorHelpRequestStatusEnum';

export interface MentorHelpRequestHistoryRequest {
  /**
   * @minLength 1
   * @maxLength 250
   * @nullable
   */
  title?: string | null;
  /**
   * @minLength 1
   * @maxLength 2000
   * @nullable
   */
  description?: string | null;
  /** @nullable */
  team?: string | null;
  /** @nullable */
  category?: MentorHelpRequestHistoryRequestCategory;
  topic: TopicEnum[];
  /** @nullable */
  reporter?: string | null;
  /** @nullable */
  mentor?: string | null;
  status?: MentorHelpRequestStatusEnum;
  /**
   * @minLength 1
   * @maxLength 100
   * @nullable
   */
  category_specialty?: string | null;
  /**
   * @minLength 1
   * @maxLength 50
   * @nullable
   */
  topic_other?: string | null;
}
