/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type MentorhelprequestshistoryListStatus = typeof MentorhelprequestshistoryListStatus[keyof typeof MentorhelprequestshistoryListStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MentorhelprequestshistoryListStatus = {
  A: 'A',
  E: 'E',
  F: 'F',
  R: 'R',
} as const;
