/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { MentorHelpRequestRequestCategory } from './mentorHelpRequestRequestCategory';
import type { TopicEnum } from './topicEnum';
import type { MentorHelpRequestStatusEnum } from './mentorHelpRequestStatusEnum';

/**
 * Base serializer that automatically scopes foreign key fields to the current event.

This serializer ensures that when validating foreign key relationships,
only objects from the current event are considered valid. This is crucial
for maintaining proper event isolation in the multi-tenant system.

Usage:
    class MySerializer(EventScopedSerializer):
        class Meta:
            model = MyModel
            fields = ['id', 'name', 'foreign_key_field']
 */
export interface MentorHelpRequestRequest {
  /**
   * @minLength 1
   * @maxLength 250
   * @nullable
   */
  title?: string | null;
  /**
   * @minLength 1
   * @maxLength 2000
   * @nullable
   */
  description?: string | null;
  team: string;
  /** @nullable */
  category?: MentorHelpRequestRequestCategory;
  topic: TopicEnum[];
  /** @nullable */
  reporter?: string | null;
  /** @nullable */
  mentor?: string | null;
  status?: MentorHelpRequestStatusEnum;
  /**
   * @minLength 1
   * @maxLength 100
   * @nullable
   */
  category_specialty?: string | null;
  /**
   * @minLength 1
   * @maxLength 50
   * @nullable
   */
  topic_other?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  reporter_location?: string | null;
}
