/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `R` - Requested
* `A` - Acknowledged
* `E` - En Route
* `F` - Resolved
 */
export type MentorHelpRequestStatusEnum = typeof MentorHelpRequestStatusEnum[keyof typeof MentorHelpRequestStatusEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MentorHelpRequestStatusEnum = {
  R: 'R',
  A: 'A',
  E: 'E',
  F: 'F',
} as const;
