/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type MentorhelprequestsListStatus = typeof MentorhelprequestsListStatus[keyof typeof MentorhelprequestsListStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MentorhelprequestsListStatus = {
  A: 'A',
  E: 'E',
  F: 'F',
  R: 'R',
} as const;
