/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { HelpRequestTeam } from './helpRequestTeam';
import type { MentorHelpRequestReadCategory } from './mentorHelpRequestReadCategory';
import type { TopicEnum } from './topicEnum';
import type { HelpRequestReporter } from './helpRequestReporter';
import type { MentorHelpRequestStatusEnum } from './mentorHelpRequestStatusEnum';

export interface MentorHelpRequestRead {
  readonly id?: string;
  /**
   * @maxLength 250
   * @nullable
   */
  title?: string | null;
  /**
   * @maxLength 2000
   * @nullable
   */
  description?: string | null;
  team: HelpRequestTeam;
  /** @nullable */
  category?: MentorHelpRequestReadCategory;
  topic: TopicEnum[];
  reporter: HelpRequestReporter;
  /** @nullable */
  mentor?: string | null;
  status?: MentorHelpRequestStatusEnum;
  /**
   * @maxLength 100
   * @nullable
   */
  category_specialty?: string | null;
  /**
   * @maxLength 50
   * @nullable
   */
  topic_other?: string | null;
  readonly created_at?: string;
  readonly updated_at?: string;
  /**
   * @maxLength 100
   * @nullable
   */
  reporter_location?: string | null;
}
