/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { MentorhelprequestshistoryListStatus } from './mentorhelprequestshistoryListStatus';

export type MentorhelprequestshistoryListParams = {
id?: string;
mentor?: string;
reporter?: string;
/**
 * A search term.
 */
search?: string;
/**
 * * `R` - Requested
* `A` - Acknowledged
* `E` - En Route
* `F` - Resolved
 */
status?: MentorhelprequestshistoryListStatus;
team?: string;
};
