/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `S` - Student
* `P` - Professional
* `H` - Hobbyist
 */
export type ParticipationCapacityEnum = typeof ParticipationCapacityEnum[keyof typeof ParticipationCapacityEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParticipationCapacityEnum = {
  S: 'S',
  P: 'P',
  H: 'H',
} as const;
