/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `P` - Participant
* `M` - Mentor
* `J` - Judge
 */
export type ParticipationClassA3fEnum = typeof ParticipationClassA3fEnum[keyof typeof ParticipationClassA3fEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParticipationClassA3fEnum = {
  P: 'P',
  M: 'M',
  J: 'J',
} as const;
