/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `R` - RSVP'd
* `C` - Confirmed
* `I` - Instructor
* `V` - Volunteer
 */
export type ParticipationEnum = typeof ParticipationEnum[keyof typeof ParticipationEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParticipationEnum = {
  R: 'R',
  C: 'C',
  I: 'I',
  V: 'V',
} as const;
