/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `P` - Participant
* `M` - Mentor
* `J` - Judge
* `S` - Sponsor
* `V` - Volunteer
* `O` - Organizer
* `G` - Guardian
* `E` - Media
 */
export type ParticipationClassEnum = typeof ParticipationClassEnum[keyof typeof ParticipationClassEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParticipationClassEnum = {
  P: 'P',
  M: 'M',
  J: 'J',
  S: 'S',
  V: 'V',
  O: 'O',
  G: 'G',
  E: 'E',
} as const;
