/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { TableNumberRequest } from './tableNumberRequest';
import type { PatchedDestinyTeamUpdateRequestTrack } from './patchedDestinyTeamUpdateRequestTrack';
import type { DestinyHardwareEnum } from './destinyHardwareEnum';

export interface PatchedDestinyTeamUpdateRequest {
  table?: TableNumberRequest;
  /** @nullable */
  track?: PatchedDestinyTeamUpdateRequestTrack;
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  round?: number;
  hardware_hack?: boolean;
  destiny_hardware?: DestinyHardwareEnum;
  attendees?: string[];
}
