/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { PreferenceEnum } from './preferenceEnum';

export interface PatchedAttendeePreferenceRequest {
  preference?: PreferenceEnum;
  preferer?: string;
  preferee?: string;
}
