/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { TableRequest } from './tableRequest';

/**
 * @nullable
 */
export type PatchedTeamUpdateRequestTable = TableRequest | null;
