/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { HistoryTypeEnum } from './historyTypeEnum';

export interface PatchedHardwareDeviceHistoryRequest {
  /** @nullable */
  hardware?: string | null;
  /**
   * @minLength 1
   * @maxLength 100
   */
  serial?: string;
  /** @nullable */
  checked_out_to?: string | null;
  history_type?: HistoryTypeEnum;
}
