/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { ShirtSizeEnum } from './shirtSizeEnum';

/**
 * @nullable
 */
export type PatchedAttendeeRSVPRequestShirtSize = ShirtSizeEnum | null;
