/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface PatchedSkillRequest {
  /**
   * @minLength 1
   * @maxLength 50
   */
  name?: string;
}
