/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { RecommendedForEnum } from './recommendedForEnum';

export interface PatchedWorkshopRequest {
  recommended_for?: RecommendedForEnum[];
  /**
   * @minLength 1
   * @maxLength 300
   */
  name?: string;
  /** @nullable */
  datetime?: string | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  duration?: number | null;
  /** @nullable */
  description?: string | null;
  /**
   * @maxLength 200
   * @nullable
   */
  course_materials?: string | null;
  /** @nullable */
  location?: string | null;
  skills?: string[];
  hardware?: string[];
}
