/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { PatchedTeamUpdateRequestTable } from './patchedTeamUpdateRequestTable';
import type { TrackEnum } from './trackEnum';
import type { DestinyHardwareEnum } from './destinyHardwareEnum';
import type { ProjectRequest } from './projectRequest';

export interface PatchedTeamUpdateRequest {
  /**
   * @minLength 1
   * @maxLength 50
   */
  name?: string;
  attendees?: string[];
  /** @nullable */
  table?: PatchedTeamUpdateRequestTable;
  /**
   * @minLength 1
   * @maxLength 2000
   * @nullable
   */
  team_description?: string | null;
  tracks?: TrackEnum[];
  destiny_hardware?: DestinyHardwareEnum[];
  project?: ProjectRequest;
  hardware_hack?: boolean;
  startup_hack?: boolean;
}
