/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { ParticipationEnum } from './participationEnum';

export interface PatchedWorkshopAttendeeRequest {
  participation?: ParticipationEnum;
  workshop?: string;
  attendee?: string;
}
