/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { UsVisaSupportNationalIdentificationDocumentTypeEnum } from './usVisaSupportNationalIdentificationDocumentTypeEnum';

/**
 * @nullable
 */
export type PatchedEventRsvpRequestUsVisaSupportNationalIdentificationDocumentType = UsVisaSupportNationalIdentificationDocumentTypeEnum | null;
