/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface PatchedEventRequest {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name?: string;
  start_date?: string;
  end_date?: string;
  /** Only one event should be active at a time */
  is_active?: boolean;
}
