/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { PatchedEventRsvpRequestParticipationRole } from './patchedEventRsvpRequestParticipationRole';
import type { PatchedEventRsvpRequestShirtSize } from './patchedEventRsvpRequestShirtSize';
import type { DietaryRestrictionsEnum } from './dietaryRestrictionsEnum';
import type { DietaryAllergiesEnum } from './dietaryAllergiesEnum';
import type { PatchedEventRsvpRequestUsVisaSupportNationalIdentificationDocumentType } from './patchedEventRsvpRequestUsVisaSupportNationalIdentificationDocumentType';
import type { PatchedEventRsvpRequestUsVisaSupportCitizenship } from './patchedEventRsvpRequestUsVisaSupportCitizenship';
import type { PatchedEventRsvpRequestSpecialInterestTrackOne } from './patchedEventRsvpRequestSpecialInterestTrackOne';
import type { PatchedEventRsvpRequestSpecialInterestTrackTwo } from './patchedEventRsvpRequestSpecialInterestTrackTwo';
import type { ParticipationClassEnum } from './participationClassEnum';
import type { PatchedEventRsvpRequestLoanerHeadsetPreference } from './patchedEventRsvpRequestLoanerHeadsetPreference';

/**
 * Base serializer that automatically scopes foreign key fields to the current event.

This serializer ensures that when validating foreign key relationships,
only objects from the current event are considered valid. This is crucial
for maintaining proper event isolation in the multi-tenant system.

Usage:
    class MySerializer(EventScopedSerializer):
        class Meta:
            model = MyModel
            fields = ['id', 'name', 'foreign_key_field']
 */
export interface PatchedEventRsvpRequest {
  /** @nullable */
  participation_role?: PatchedEventRsvpRequestParticipationRole;
  event?: string;
  /** @nullable */
  shirt_size?: PatchedEventRsvpRequestShirtSize;
  /**
   * I.e., a Discord username
   * @minLength 1
   * @maxLength 40
   * @nullable
   */
  communication_platform_username?: string | null;
  dietary_restrictions?: DietaryRestrictionsEnum[];
  /**
   * @minLength 1
   * @maxLength 40
   * @nullable
   */
  dietary_restrictions_other?: string | null;
  dietary_allergies?: DietaryAllergiesEnum[];
  /**
   * @minLength 1
   * @maxLength 40
   * @nullable
   */
  dietary_allergies_other?: string | null;
  /**
   * @minLength 1
   * @maxLength 200
   * @nullable
   */
  additional_accommodations?: string | null;
  us_visa_support_is_required?: boolean;
  /** @nullable */
  us_visa_letter_of_invitation_required?: boolean | null;
  /**
   * @minLength 1
   * @maxLength 200
   * @nullable
   */
  us_visa_support_full_name?: string | null;
  /**
   * @minLength 1
   * @maxLength 50
   * @nullable
   */
  us_visa_support_document_number?: string | null;
  /** @nullable */
  us_visa_support_national_identification_document_type?: PatchedEventRsvpRequestUsVisaSupportNationalIdentificationDocumentType;
  /** @nullable */
  us_visa_support_citizenship?: PatchedEventRsvpRequestUsVisaSupportCitizenship;
  /**
   * @minLength 1
   * @maxLength 500
   * @nullable
   */
  us_visa_support_address?: string | null;
  /**
   * Will you be under 18 on January 22, 2026
   * @nullable
   */
  under_18_by_date?: boolean | null;
  /** @nullable */
  parental_consent_form_signed?: boolean | null;
  agree_to_media_release?: boolean;
  agree_to_liability_release?: boolean;
  agree_to_rules_code_of_conduct?: boolean;
  /**
   * @minLength 1
   * @maxLength 200
   */
  emergency_contact_name?: string;
  /**
   * @minLength 1
   * @maxLength 128
   */
  personal_phone_number?: string;
  /**
   * @minLength 1
   * @maxLength 128
   */
  emergency_contact_phone_number?: string;
  /**
   * @minLength 1
   * @maxLength 254
   */
  emergency_contact_email?: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  emergency_contact_relationship?: string;
  /** @nullable */
  special_interest_track_one?: PatchedEventRsvpRequestSpecialInterestTrackOne;
  /** @nullable */
  special_interest_track_two?: PatchedEventRsvpRequestSpecialInterestTrackTwo;
  /**
   * AR or VR apps in any store? And if so, which ones?
   * @minLength 1
   * @maxLength 250
   * @nullable
   */
  app_in_store?: string | null;
  /**
   * @minLength 1
   * @maxLength 250
   * @nullable
   */
  currently_build_for_xr?: string | null;
  /**
   * @minLength 1
   * @maxLength 250
   * @nullable
   */
  currently_use_xr?: string | null;
  /**
   * @minLength 1
   * @maxLength 250
   * @nullable
   */
  non_xr_talents?: string | null;
  /**
   * @minLength 1
   * @maxLength 250
   * @nullable
   */
  ar_vr_ap_in_store?: string | null;
  reality_hack_project_to_product?: boolean;
  participation_class?: ParticipationClassEnum;
  /**
   * @minLength 1
   * @maxLength 100
   * @nullable
   */
  sponsor_company?: string | null;
  /**
   * @minLength 1
   * @maxLength 2000
   * @nullable
   */
  breakthrough_hacks_interest?: string | null;
  /** @nullable */
  loaner_headset_preference?: PatchedEventRsvpRequestLoanerHeadsetPreference;
}
