/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `Y` - Yay
* `N` - Nay
* `T` - Tbd
 */
export type PreferenceEnum = typeof PreferenceEnum[keyof typeof PreferenceEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreferenceEnum = {
  Y: 'Y',
  N: 'N',
  T: 'T',
} as const;
