/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface ProjectRequest {
  /**
   * @minLength 1
   * @maxLength 50
   */
  name: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  repository_location: string;
  /**
   * @minLength 1
   * @maxLength 1000
   */
  description: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  submission_location: string;
  /** @nullable */
  team?: string | null;
  /**
   * @maxLength 75
   * @nullable
   */
  census_taker_name?: string | null;
  /**
   * @maxLength 75
   * @nullable
   */
  census_location_override?: string | null;
  /**
   * @maxLength 75
   * @nullable
   */
  team_primary_contact?: string | null;
}
