/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * Base serializer that automatically scopes foreign key fields to the current event.

This serializer ensures that when validating foreign key relationships,
only objects from the current event are considered valid. This is crucial
for maintaining proper event isolation in the multi-tenant system.

Usage:
    class MySerializer(EventScopedSerializer):
        class Meta:
            model = MyModel
            fields = ['id', 'name', 'foreign_key_field']
 */
export interface ProjectRequest {
  /**
   * @minLength 1
   * @maxLength 50
   */
  name: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  repository_location: string;
  /**
   * @minLength 1
   * @maxLength 1000
   */
  description: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  submission_location: string;
  /** @nullable */
  team?: string | null;
  /**
   * @maxLength 75
   * @nullable
   */
  census_taker_name?: string | null;
  /**
   * @maxLength 75
   * @nullable
   */
  census_location_override?: string | null;
  /**
   * @maxLength 75
   * @nullable
   */
  team_primary_contact?: string | null;
}
