/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * Slim read-only event serializer safe for unauthenticated responses.
 */
export interface PublicEvent {
  readonly id?: string;
  /** @maxLength 100 */
  name: string;
  start_date: string;
  end_date: string;
}
