/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `S` - Single Choice
* `M` - Multiple Choice
* `T` - Text Response
* `L` - Long Text/Essay
 */
export type QuestionTypeEnum = typeof QuestionTypeEnum[keyof typeof QuestionTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuestionTypeEnum = {
  S: 'S',
  M: 'M',
  T: 'T',
  L: 'L',
} as const;
