/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `B` - Black, African American, or of African descent
* `C` - Hispanic, Latino, Latina, Latinx, or of Latinx or Spanish-speaking descent
* `D` - Middle Eastern, North African, or of North African descent
* `E` - Native American, American Indian, Alaska Native, or Indigenous
* `F` - Pacific Islander or Native Hawaiian
* `G` - White or of European descent
* `H` - Multi-racial or multi-ethnic
* `I` - I prefer not to say
* `J` - East Asian
* `K` - South Asian
* `L` - Southeast Asian
* `M` - Central Asian
* `O` - Other
 */
export type RaceEthnicGroupEnum = typeof RaceEthnicGroupEnum[keyof typeof RaceEthnicGroupEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RaceEthnicGroupEnum = {
  B: 'B',
  C: 'C',
  D: 'D',
  E: 'E',
  F: 'F',
  G: 'G',
  H: 'H',
  I: 'I',
  J: 'J',
  K: 'K',
  L: 'L',
  M: 'M',
  O: 'O',
} as const;
