/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `A` - Digital/Creative Designer
* `D` - Developer
* `S` - Domain or other Specialized Skill Expert
* `P` - Project Manager
 */
export type RecommendedForEnum = typeof RecommendedForEnum[keyof typeof RecommendedForEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecommendedForEnum = {
  A: 'A',
  D: 'D',
  S: 'S',
  P: 'P',
} as const;
