/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `MH` - Morss Hall
* `AT` - Atlantis
* `NE` - Neptune
* `24` - 32-124
* `44` - 32-144
* `41` - 32-141
* `MZ` - Mezzanine
* `TC` - Twenty Chimneys
* `301` - W20-301+302
* `SP` - Sala de Puerto Rico
* `401` - W20-401
* `RM` - Remote
 */
export type RoomEnum = typeof RoomEnum[keyof typeof RoomEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoomEnum = {
  MH: 'MH',
  AT: 'AT',
  NE: 'NE',
  NUMBER_24: '24',
  NUMBER_44: '44',
  NUMBER_41: '41',
  MZ: 'MZ',
  TC: 'TC',
  NUMBER_301: '301',
  SP: 'SP',
  NUMBER_401: '401',
  RM: 'RM',
} as const;
