/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `MH` - Morss Hall
* `AT` - Atlantis
* `NE` - Neptune
* `24` - 32-124
* `44` - 32-144
* `41` - 32-141
 */
export type RoomEnum = typeof RoomEnum[keyof typeof RoomEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoomEnum = {
  MH: 'MH',
  AT: 'AT',
  NE: 'NE',
  NUMBER_24: '24',
  NUMBER_44: '44',
  NUMBER_41: '41',
} as const;
