/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { RsvpsListParticipationClass } from './rsvpsListParticipationClass';
import type { RsvpsListParticipationRole } from './rsvpsListParticipationRole';

export type RsvpsListParams = {
checked_in_at?: string;
communications_platform_username?: string;
email?: string;
first_name?: string;
last_name?: string;
/**
 * * `P` - Participant
* `M` - Mentor
* `J` - Judge
* `S` - Sponsor
* `V` - Volunteer
* `O` - Organizer
* `G` - Guardian
* `E` - Media
 */
participation_class?: RsvpsListParticipationClass;
/**
 * * `A` - Digital/Creative Designer
* `D` - Developer
* `S` - Domain or other Specialized Skill Expert
* `P` - Project Manager
 */
participation_role?: RsvpsListParticipationRole;
/**
 * A search term.
 */
search?: string;
};
