/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { RsvpResponseChoicesSnapshot } from './rsvpResponseChoicesSnapshot';
import type { RsvpResponseSelectedKeysSnapshot } from './rsvpResponseSelectedKeysSnapshot';

/**
 * Serializer for RSVP question responses with snapshots
 */
export interface RsvpResponse {
  readonly id?: string;
  question: string;
  question_text_snapshot: string;
  choices_snapshot?: RsvpResponseChoicesSnapshot;
  selected_keys_snapshot?: RsvpResponseSelectedKeysSnapshot;
  readonly selected_choice_keys?: readonly string[];
  text_response?: string;
  text_response_snapshot?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
}
