/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type SchemaSpectacularRetrieveFormat = typeof SchemaSpectacularRetrieveFormat[keyof typeof SchemaSpectacularRetrieveFormat];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SchemaSpectacularRetrieveFormat = {
  json: 'json',
  yaml: 'yaml',
} as const;
