/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { SchemaSpectacularRetrieveFormat } from './schemaSpectacularRetrieveFormat';
import type { SchemaSpectacularRetrieveLang } from './schemaSpectacularRetrieveLang';

export type SchemaSpectacularRetrieveParams = {
format?: SchemaSpectacularRetrieveFormat;
lang?: SchemaSpectacularRetrieveLang;
};
