/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `1` - XS
* `2` - S
* `3` - M
* `4` - L
* `5` - XL
* `6` - XXL
 */
export type ShirtSizeEnum = typeof ShirtSizeEnum[keyof typeof ShirtSizeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ShirtSizeEnum = {
  NUMBER_1: '1',
  NUMBER_2: '2',
  NUMBER_3: '3',
  NUMBER_4: '4',
  NUMBER_5: '5',
  NUMBER_6: '6',
} as const;
