/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { Skill } from './skill';
import type { ProficiencyEnum } from './proficiencyEnum';
import type { Attendee } from './attendee';

export interface SkillProficiencyDetail {
  readonly id?: string;
  skill: Skill;
  proficiency?: ProficiencyEnum;
  attendee: Attendee;
  readonly created_at?: string;
  readonly updated_at?: string;
}
