/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { Skill } from './skill';
import type { ProficiencyEnum } from './proficiencyEnum';

export interface SkillProficiencyAttendee {
  readonly id?: string;
  skill: Skill;
  proficiency?: ProficiencyEnum;
}
