/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { ProficiencyEnum } from './proficiencyEnum';

export interface SkillProficiencyCreateRequest {
  skill: string;
  proficiency?: ProficiencyEnum;
  /** @nullable */
  attendee: string | null;
}
