/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface TableCreate {
  readonly id?: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  number: number;
  /** @nullable */
  location?: string | null;
}
