/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `AC` - AC
* `SE` - SE
* `VR` - VR
* `AR` - AR
* `MR` - MR
* `CO` - CO
* `HA` - HA
* `CA` - CA
* `TA` - TA
* `HD` - HD
 */
export type TagsEnum = typeof TagsEnum[keyof typeof TagsEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TagsEnum = {
  AC: 'AC',
  SE: 'SE',
  VR: 'VR',
  AR: 'AR',
  MR: 'MR',
  CO: 'CO',
  HA: 'HA',
  CA: 'CA',
  TA: 'TA',
  HD: 'HD',
} as const;
