/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { TrackEnum } from './trackEnum';
import type { DestinyHardwareEnum } from './destinyHardwareEnum';

export interface Team {
  readonly id?: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  number?: number | null;
  /** @maxLength 50 */
  name: string;
  attendees?: string[];
  /** @nullable */
  table?: string | null;
  tracks?: TrackEnum;
  destiny_hardware?: DestinyHardwareEnum;
  /**
   * @maxLength 2000
   * @nullable
   */
  team_description?: string | null;
  readonly created_at?: string;
  readonly updated_at?: string;
}
