/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type TeamsListParams = {
attendees?: string[];
name?: string;
/**
 * A search term.
 */
search?: string;
table?: string;
table__number?: number;
};
