/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { AnnouncementPendingEnum } from './announcementPendingEnum';
import type { MentorHelpRequestStatusEnum } from './mentorHelpRequestStatusEnum';

export interface TeamLightHouse {
  readonly id?: string;
  announcement_pending?: AnnouncementPendingEnum;
  mentor_requested?: MentorHelpRequestStatusEnum;
  readonly created_at?: string;
  readonly updated_at?: string;
}
