/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { AttendeeName } from './attendeeName';
import type { TeamTable } from './teamTable';
import type { TeamProject } from './teamProject';
import type { TeamLightHouse } from './teamLightHouse';
import type { TeamDetailTracks } from './teamDetailTracks';
import type { TeamDetailDestinyHardware } from './teamDetailDestinyHardware';

export interface TeamDetail {
  readonly id?: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  number?: number | null;
  /** @maxLength 50 */
  name: string;
  attendees: AttendeeName[];
  table: TeamTable;
  hardware_hack?: boolean;
  startup_hack?: boolean;
  community_hack?: boolean;
  project: TeamProject;
  lighthouse: TeamLightHouse;
  /** @nullable */
  tracks?: TeamDetailTracks;
  /** @nullable */
  destiny_hardware?: TeamDetailDestinyHardware;
  readonly event_tracks?: string;
  readonly event_destiny_hardware?: string;
  /**
   * @maxLength 2000
   * @nullable
   */
  team_description?: string | null;
  readonly created_at?: string;
  readonly updated_at?: string;
}
