/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface TeamCreateRequest {
  /**
   * @minLength 1
   * @maxLength 50
   */
  name: string;
  attendees?: string[];
  /** @nullable */
  table?: string | null;
  /**
   * @minLength 1
   * @maxLength 2000
   * @nullable
   */
  team_description?: string | null;
}
