/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { TeamUpdateTable } from './teamUpdateTable';
import type { TrackEnum } from './trackEnum';
import type { DestinyHardwareEnum } from './destinyHardwareEnum';
import type { Project } from './project';

export interface TeamUpdate {
  readonly id?: string;
  /** @maxLength 50 */
  name: string;
  attendees?: string[];
  /** @nullable */
  table: TeamUpdateTable;
  /**
   * @maxLength 2000
   * @nullable
   */
  team_description?: string | null;
  tracks: TrackEnum[];
  destiny_hardware: DestinyHardwareEnum[];
  project: Project;
  hardware_hack?: boolean;
  startup_hack?: boolean;
}
