/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface TeamCreate {
  readonly id?: string;
  /** @maxLength 50 */
  name: string;
  attendees?: string[];
  /** @nullable */
  table?: string | null;
  /**
   * @maxLength 2000
   * @nullable
   */
  team_description?: string | null;
}
