/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { TeamTracks } from './teamTracks';
import type { TeamDestinyHardware } from './teamDestinyHardware';
import type { TeamProject } from './teamProject';

/**
 * Base serializer that automatically scopes foreign key fields to the current event.

This serializer ensures that when validating foreign key relationships,
only objects from the current event are considered valid. This is crucial
for maintaining proper event isolation in the multi-tenant system.

Usage:
    class MySerializer(EventScopedSerializer):
        class Meta:
            model = MyModel
            fields = ['id', 'name', 'foreign_key_field']
 */
export interface Team {
  readonly id?: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  number?: number | null;
  /** @maxLength 50 */
  name: string;
  attendees?: string[];
  /** @nullable */
  table?: string | null;
  /** @nullable */
  tracks?: TeamTracks;
  /** @nullable */
  destiny_hardware?: TeamDestinyHardware;
  /**
   * @maxLength 2000
   * @nullable
   */
  team_description?: string | null;
  readonly created_at?: string;
  readonly updated_at?: string;
  project: TeamProject;
  startup_hack?: boolean;
  community_hack?: boolean;
  hardware_hack?: boolean;
  readonly event_tracks?: string;
  readonly event_destiny_hardware?: string;
}
