/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface TeamProject {
  readonly id?: string;
  /** @maxLength 50 */
  name: string;
  /** @maxLength 200 */
  repository_location: string;
  /** @maxLength 200 */
  submission_location: string;
  /**
   * @maxLength 75
   * @nullable
   */
  census_location_override?: string | null;
  /**
   * @maxLength 75
   * @nullable
   */
  census_taker_name?: string | null;
  /**
   * @maxLength 75
   * @nullable
   */
  team_primary_contact?: string | null;
  /** @maxLength 1000 */
  description: string;
  readonly created_at?: string;
  readonly updated_at?: string;
}
