/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `Y` - Yes
* `N` - No
 */
export type ThemeDetailEnum = typeof ThemeDetailEnum[keyof typeof ThemeDetailEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ThemeDetailEnum = {
  Y: 'Y',
  N: 'N',
} as const;
