/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `Y` - Yes
* `N` - No
 */
export type ThemeInterestTrackEnum = typeof ThemeInterestTrackEnum[keyof typeof ThemeInterestTrackEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ThemeInterestTrackEnum = {
  Y: 'Y',
  N: 'N',
} as const;
