/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `EC` - Ecosystem
* `T1` - Tier 1
* `T2` - Tier 2
* `T3` - Tier 3
* `T4` - Tier 4
* `T5` - Tier 5
 */
export type TierEnum = typeof TierEnum[keyof typeof TierEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TierEnum = {
  EC: 'EC',
  T1: 'T1',
  T2: 'T2',
  T3: 'T3',
  T4: 'T4',
  T5: 'T5',
} as const;
