/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `C` - Open Lab (AKA Community Hack)
* `S` - Connecting for Change with Social XR
* `E` - Augmented Design & Engineering
* `D` - Standing on the Shoulders of Sustainability
* `A` - AeroSpatial Exploration
* `L` - Augmented Intelligence
* `H` - Healthcare
 */
export type TrackEnum = typeof TrackEnum[keyof typeof TrackEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TrackEnum = {
  C: 'C',
  S: 'S',
  E: 'E',
  D: 'D',
  A: 'A',
  L: 'L',
  H: 'H',
} as const;
