/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type UploadedFilesListParams = {
claimed?: boolean;
/**
 * A search term.
 */
search?: string;
};
