/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `P` - Passport
* `N` - National/State/Municipal ID
 */
export type UsVisaSupportNationalIdentificationDocumentTypeEnum = typeof UsVisaSupportNationalIdentificationDocumentTypeEnum[keyof typeof UsVisaSupportNationalIdentificationDocumentTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsVisaSupportNationalIdentificationDocumentTypeEnum = {
  P: 'P',
  N: 'N',
} as const;
