/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { ParticipationEnum } from './participationEnum';

export interface WorkshopAttendeeRequest {
  participation?: ParticipationEnum;
  workshop: string;
  attendee: string;
}
