/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type WorkshopattendeesListParticipation = typeof WorkshopattendeesListParticipation[keyof typeof WorkshopattendeesListParticipation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkshopattendeesListParticipation = {
  C: 'C',
  I: 'I',
  R: 'R',
  V: 'V',
} as const;
