/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { Workshop } from './workshop';
import type { ParticipationEnum } from './participationEnum';

export interface WorkshopAttendeeWorkshopDetail {
  readonly id?: string;
  workshop: Workshop;
  participation?: ParticipationEnum;
  readonly created_at?: string;
  readonly updated_at?: string;
}
