/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { ParticipationEnum } from './participationEnum';

export interface WorkshopAttendee {
  readonly id?: string;
  participation?: ParticipationEnum;
  readonly created_at?: string;
  readonly updated_at?: string;
  workshop: string;
  attendee: string;
}
