/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { WorkshopattendeesListParticipation } from './workshopattendeesListParticipation';

export type WorkshopattendeesListParams = {
attendee?: string;
/**
 * * `R` - RSVP'd
* `C` - Confirmed
* `I` - Instructor
* `V` - Volunteer
 */
participation?: WorkshopattendeesListParticipation;
/**
 * A search term.
 */
search?: string;
workshop?: string;
};
