/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { WorkshopsListRecommendedFor } from './workshopsListRecommendedFor';

export type WorkshopsListParams = {
datetime?: string;
hardware?: string[];
location?: string;
/**
 * * `A` - Digital/Creative Designer
* `D` - Developer
* `S` - Domain or other Specialized Skill Expert
* `P` - Project Manager
 */
recommended_for?: WorkshopsListRecommendedFor;
/**
 * A search term.
 */
search?: string;
};
